/*
 *
 * OrgPage constants
 *
 */

export const OPEN_EDIT_COLOR_DIALOG = 'app/OrgPage/OPEN_EDIT_COLOR_DIALOG';
export const CLOSE_EDIT_COLOR_DIALOG = 'app/OrgPage/CLOSE_EDIT_COLOR_DIALOG';

export const OPEN_EDIT_COMPANY_DIALOG = 'app/OrgPage/OPEN_EDIT_COMPANY_DIALOG';
export const CLOSE_EDIT_COMPANY_DIALOG =
  'app/OrgPage/CLOSE_EDIT_COMPANY_DIALOG';

export const OPEN_NEW_BRANCH_DIALOG = 'app/OrgPage/OPEN_NEW_BRANCH_DIALOG';
export const CLOSE_NEW_BRANCH_DIALOG = 'app/OrgPage/CLOSE_NEW_BRANCH_DIALOG';
export const OPEN_EDIT_BRANCH_DIALOG = 'app/OrgPage/OPEN_EDIT_BRANCH_DIALOG';
export const CLOSE_EDIT_BRANCH_DIALOG = 'app/OrgPage/CLOSE_EDIT_BRANCH_DIALOG';

export const OPEN_NEW_DEPARTMENT_DIALOG =
  'app/OrgPage/OPEN_NEW_DEPARTMENT_DIALOG';
export const CLOSE_NEW_DEPARTMENT_DIALOG =
  'app/OrgPage/CLOSE_NEW_DEPARTMENT_DIALOG';
export const OPEN_EDIT_DEPARTMENT_DIALOG =
  'app/OrgPage/OPEN_EDIT_DEPARTMENT_DIALOG';
export const CLOSE_EDIT_DEPARTMENT_DIALOG =
  'app/OrgPage/CLOSE_EDIT_DEPARTMENT_DIALOG';

export const OPEN_NEW_PARTY_DIALOG = 'app/OrgPage/OPEN_NEW_PARTY_DIALOG';
export const CLOSE_NEW_PARTY_DIALOG = 'app/OrgPage/CLOSE_NEW_PARTY_DIALOG';
export const OPEN_EDIT_PARTY_DIALOG = 'app/OrgPage/OPEN_EDIT_PARTY_DIALOG';
export const CLOSE_EDIT_PARTY_DIALOG = 'app/OrgPage/CLOSE_EDIT_PARTY_DIALOG';

// Add new sub group
export const OPEN_NEW_SUB_PARTY_DIALOG = 'app/OrgPage/OPEN_NEW_SUB_PARTY_DIALOG';
export const CLOSE_NEW_SUB_PARTY_DIALOG = 'app/OrgPage/CLOSE_NEW_SUB_PARTY_DIALOG';