/*
 *
 * OrgPage constants
 *
 */

export const OPEN_EDIT_COLOR_DIALOG = 'app/OrgPage/OPEN_EDIT_COLOR_DIALOG';
export const CLOSE_EDIT_COLOR_DIALOG = 'app/OrgPage/CLOSE_EDIT_COLOR_DIALOG';

export const OPEN_EDIT_COMPANY_DIALOG = 'app/OrgPage/OPEN_EDIT_COMPANY_DIALOG';
export const CLOSE_EDIT_COMPANY_DIALOG = 'app/OrgPage/CLOSE_EDIT_COMPANY_DIALOG';

export const OPEN_NEW_BRANCH_DIALOG = 'app/OrgPage/OPEN_NEW_BRANCH_DIALOG';
export const CLOSE_NEW_BRANCH_DIALOG = 'app/OrgPage/CLOSE_NEW_BRANCH_DIALOG';
export const OPEN_EDIT_BRANCH_DIALOG = 'app/OrgPage/OPEN_EDIT_BRANCH_DIALOG';
export const CLOSE_EDIT_BRANCH_DIALOG = 'app/OrgPage/CLOSE_EDIT_BRANCH_DIALOG';

export const OPEN_NEW_DEPARTMENT_DIALOG = 'app/OrgPage/OPEN_NEW_DEPARTMENT_DIALOG';
export const CLOSE_NEW_DEPARTMENT_DIALOG = 'app/OrgPage/CLOSE_NEW_DEPARTMENT_DIALOG';
export const OPEN_EDIT_DEPARTMENT_DIALOG = 'app/OrgPage/OPEN_EDIT_DEPARTMENT_DIALOG';
export const CLOSE_EDIT_DEPARTMENT_DIALOG = 'app/OrgPage/CLOSE_EDIT_DEPARTMENT_DIALOG';

export const GET_COMPANY_INFO = 'app/OrgPage/GET_COMPANY_INFO';
export const GET_COMPANY_INFO_SUCCESS = 'app/OrgPage/GET_COMPANY_INFO_SUCCESS';
export const GET_COMPANY_INFO_ERROR = 'app/OrgPage/GET_COMPANY_INFO_ERROR';

export const UPDATE_COMPANY_INFO = 'app/OrgPage/UPDATE_COMPANY_INFO';
export const UPDATE_COMPANY_INFO_SUCCESS = 'app/OrgPage/UPDATE_COMPANY_INFO_SUCCESS';
export const UPDATE_COMPANY_INFO_ERROR = 'app/OrgPage/UPDATE_COMPANY_INFO_ERROR';
