/*
 *
 * OrgPage constants
 *
 */

export const OPEN_FILE_UPLOAD_DIALOG = 'app/UtilityPage/OPEN_FILE_UPLOAD_DIALOG';
export const CLOSE_FILE_UPLOAD_DIALOG = 'app/UtilityPage/CLOSE_FILE_UPLOAD_DIALOG';

export const OPEN_SHARE_FILE_DIALOG = 'app/UtilityPage/OPEN_SHARE_FILE_DIALOG';
export const CLOSE_SHARE_FILE_DIALOG = 'app/UtilityPage/CLOSE_SHARE_FILE_DIALOG';

export const OPEN_EDIT_COMPANY_DIALOG = 'app/UtilityPage/OPEN_EDIT_COMPANY_DIALOG';
export const CLOSE_EDIT_COMPANY_DIALOG =
  'app/UtilityPage/CLOSE_EDIT_COMPANY_DIALOG';

export const OPEN_NEW_BRANCH_DIALOG = 'app/UtilityPage/OPEN_NEW_BRANCH_DIALOG';
export const CLOSE_NEW_BRANCH_DIALOG = 'app/UtilityPage/CLOSE_NEW_BRANCH_DIALOG';
export const OPEN_EDIT_BRANCH_DIALOG = 'app/UtilityPage/OPEN_EDIT_BRANCH_DIALOG';
export const CLOSE_EDIT_BRANCH_DIALOG = 'app/UtilityPage/CLOSE_EDIT_BRANCH_DIALOG';

export const OPEN_NEW_DEPARTMENT_DIALOG =
  'app/OrgPage/OPEN_NEW_DEPARTMENT_DIALOG';
export const CLOSE_NEW_DEPARTMENT_DIALOG =
  'app/OrgPage/CLOSE_NEW_DEPARTMENT_DIALOG';
export const OPEN_EDIT_DEPARTMENT_DIALOG =
  'app/OrgPage/OPEN_EDIT_DEPARTMENT_DIALOG';
export const CLOSE_EDIT_DEPARTMENT_DIALOG =
  'app/OrgPage/CLOSE_EDIT_DEPARTMENT_DIALOG';
