/*
 *
 * UtilityPage constants
 *
 */

export const OPEN_FILE_UPLOAD_DIALOG = 'app/UtilityPage/OPEN_FILE_UPLOAD_DIALOG';
export const CLOSE_FILE_UPLOAD_DIALOG = 'app/UtilityPage/CLOSE_FILE_UPLOAD_DIALOG';

export const OPEN_SHARE_FILE_DIALOG = 'app/UtilityPage/OPEN_SHARE_FILE_DIALOG';
export const CLOSE_SHARE_FILE_DIALOG = 'app/UtilityPage/CLOSE_SHARE_FILE_DIALOG';

export const OPEN_NEW_TASK_DIALOG = 'app/UtilityPage/OPEN_NEW_TASK_DIALOG';
export const CLOSE_NEW_TASK_DIALOG = 'app/UtilityPage/CLOSE_NEW_TASK_DIALOG';

export const OPEN_NEW_FILE_DIALOG = 'app/UtilityPage/OPEN_NEW_TASK_DIALOG';
export const CLOSE_NEW_FILE_DIALOG = 'app/UtilityPage/CLOSE_NEW_TASK_DIALOG';

export const OPEN_TASK_PREVIEW_DIALOG = 'app/UtilityPage/OPEN_TASK_PREVIEW_DIALOG';
export const CLOSE_TASK_PREVIEW_DIALOG = 'app/UtilityPage/CLOSE_TASK_PREVIEW_DIALOG';

export const OPEN_NEW_BRANCH_DIALOG = 'app/UtilityPage/OPEN_NEW_BRANCH_DIALOG';
export const CLOSE_NEW_BRANCH_DIALOG = 'app/UtilityPage/CLOSE_NEW_BRANCH_DIALOG';
export const OPEN_EDIT_BRANCH_DIALOG = 'app/UtilityPage/OPEN_EDIT_BRANCH_DIALOG';
export const CLOSE_EDIT_BRANCH_DIALOG = 'app/UtilityPage/CLOSE_EDIT_BRANCH_DIALOG';

export const OPEN_NEW_DEPARTMENT_DIALOG = 'app/OrgPage/OPEN_NEW_DEPARTMENT_DIALOG';
export const CLOSE_NEW_DEPARTMENT_DIALOG = 'app/OrgPage/CLOSE_NEW_DEPARTMENT_DIALOG';
export const OPEN_EDIT_DEPARTMENT_DIALOG = 'app/OrgPage/OPEN_EDIT_DEPARTMENT_DIALOG';
export const CLOSE_EDIT_DEPARTMENT_DIALOG = 'app/OrgPage/CLOSE_EDIT_DEPARTMENT_DIALOG';

// UTILITY CONSTANTS
export const GET_UTILITY_APPS = 'app/UtilityPage/GET UTILITY APPS';
export const GET_UTILITY_APPS_SUCCESS = 'app/UtilityPage/GET UTILITY APPS SUCCESS';
export const GET_UTILITY_APPS_ERROR = 'app/UtilityPage/GET UTILITY APPS ERROR';

export const GET_UTILITY_TASKS = 'app/UtilityPage/GET UTILITY TASKS';
export const CREATE_UTILITY_TASKS = 'app/UtilityPage/CREATE UTILITY TASKS';
export const CREATE_UTILITY_TASKS_SUCCESS = 'app/UtilityPage/CREATE UTILITY TASKS SUCCESS';
export const GET_UTILITY_TASKS_ERROR = 'app/UtilityPage/GET UTILITY TASKS ERROR';

export const GET_UTILITY_FILES = 'app/UtilityPage/GET UTILITY FILES';
export const CREATE_UTILITY_FILES = 'app/UtilityPage/CREATE UTILITY FILES';
export const CREATE_UTILITY_FILES_SUCCESS = 'app/UtilityPage/CREATE UTILITY FILES SUCCESS';
export const GET_UTILITY_FILES_ERROR = 'app/UtilityPage/GET UTILITY FILES ERROR';

export const GET_UTILITY_CHATS = 'app/UtilityPage/GET UTILITY CHATS ';
export const CREATE_UTILITY_CHATS_SUCCESS = 'app/UtilityPage/CREATE UTILITY CHATS SUCCESS';
export const GET_UTILITY_CHATS_ERROR = 'app/UtilityPage/GET UTILITY CHATS ERROR';
