/*
 *
 * UsersPage constants
 *
 */

export const GET_ALL_EMPLOYEES = 'app/UsersPage/GET_ALL_EMPLOYEES';
export const GET_ALL_EMPLOYEES_SUCCESS =
  'app/UsersPage/GET_ALL_EMPLOYEES_EMPLOYEE';
export const GET_ALL_EMPLOYEES_ERROR = 'app/UsersPage/GET_ALL_EMPLOYEES_ERROR';

export const OPEN_NEW_EMPLOYEE_DIALOG =
  'app/UsersPage/OPEN_NEW_EMPLOYEE_DIALOG';
export const CLOSE_NEW_EMPLOYEE_DIALOG =
  'app/UsersPage/CLOSE_NEW_EMPLOYEE_DIALOG';

export const OPEN_EDIT_EMPLOYEE_DIALOG =
  'app/UsersPage/OPEN_EDIT_EMPLOYEE_DIALOG';
export const CLOSE_EDIT_EMPLOYEE_DIALOG =
  'app/UsersPage/CLOSE_EDIT_EMPLOYEE_DIALOG';

export const OPEN_VIEW_EMPLOYEE_DIALOG =
  'app/UsersPage/OPEN_VIEW_EMPLOYEE_DIALOG';
export const CLOSE_VIEW_EMPLOYEE_DIALOG =
  'app/UsersPage/CLOSE_VIEW_EMPLOYEE_DIALOG';

export const CREATE_NEW_EMPLOYEE = 'app/UsersPage/CREATE_NEW_EMPLOYEE';
export const CREATE_NEW_EMPLOYEE_SUCCESS =
  'app/UsersPage/CREATE_NEW_EMPLOYEE_SUCCESS';
export const CREATE_NEW_EMPLOYEE_ERROR =
  'app/UsersPage/CREATE_NEW_EMPLOYEE_ERROR';